on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: Chryz-Hub
          label: invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '<h3>Welcome to <b><a href="https://chryz-hub.github.io/">ChryzHub</a></b></h3><p><b>Invitation Request Sent</p></b>An invitation request has been sent to your GitHub registered E-mail address, so accept it now to join the community before it expires. To connect with the community, check out the <a href="https://chryz-hub.github.io/connect/">ChryzHub Connect Website</a><br> Do make your <a href="https://github.com/chryz-hub/opensource-4-everyone/blob/master/membership-visibility.md">membership visibility public</a> and also add your name been a member of the community <a href="https://github.com/chryz-hub/chryz-hub.github.io/blob/master/CONTRIBUTORS.md">here</a>.</p>To make a practice pull request <a href="https://github.com/chryz-hub/opensource-4-everyone/blob/master/My-PR-Contribution-Practice.md">click here</a><p> Do not forget, open-source is beyond coding but the coming together of people, ideas, communicating, adding values and solving problems.</p>'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
